#!/usr/bin/env python3
"""Generate app/settings/field_catalog.py from the pulled SCM OpenAPI specs.

The field catalog gives generated ``set`` commands real CLI field syntax
(``set cngfw tags web color Red``) instead of a raw ``json '{...}'`` blob.
For every resource-catalog entry with ``method == POST``, a ``set `` command
and no path params, this script resolves the request-body schema and emits:

* ``args``    — ordered CLI argument specs (consumed by
  ``app/settings/command_structure.py``): required positionals first
  (``name`` leading), then an optional variant ``type``/``value`` pair,
  then optional keyword fields.
* ``payload`` — payload-building metadata (consumed by
  ``app/commands/generated.py``): CLI-field → API-property map, the fields
  whose API value is a string array, and the variant-group mapping.

Schema handling: local ``$ref`` resolution (cycle-guarded), ``allOf``
property/required merging, and top-level ``anyOf``/``oneOf`` groups.  A group
of single-scalar-property variants becomes a CLI ``type`` choice + ``value``
slot; the folder/snippet/device container group is skipped (ARC supplies the
folder from context via a query param).  Resources are skipped entirely when
any required property is a nested object/array we cannot express as flat CLI
fields, when there is more than one variant group, or when no usable fields
remain.
"""

from __future__ import annotations

import difflib
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

SPECS_DIR = REPO_ROOT / "docs" / "scm-api" / "specs"
CATALOG_FILE = REPO_ROOT / "app" / "settings" / "field_catalog.py"

#: Variant groups whose property names are a subset of this set are the
#: "container" choice (folder/snippet/device) — ARC supplies the folder from
#: session context as a query parameter, so the group is not a CLI field.
_CONTAINER_PROPS = {"folder", "snippet", "device"}

_SCALAR_TYPES = {"string", "integer", "number", "boolean"}

_HEADER = '''"""AUTO-GENERATED CLI field catalog — DO NOT EDIT BY HAND.

Generated by ``dev/generate_field_library.py`` from the pulled SCM OpenAPI
specs. Maps generated `set` commands to CLI argument specs (consumed by
app/settings/command_structure.py) and payload-building metadata (consumed
by app/commands/generated.py). Regenerate:
    python dev/generate_field_library.py   (runs automatically on docsupdate)
"""

# NOTE: boolean/integer fields stay plain value/keyword args — the CLI sends
# the string form in the JSON payload and the SCM API coerces the type.

FIELD_CATALOG: dict[str, dict] = {
'''


# ---------------------------------------------------------------------------
# Schema plumbing
# ---------------------------------------------------------------------------

_spec_cache: dict[str, dict] = {}


def _load_spec(spec_key: str) -> dict:
    if spec_key not in _spec_cache:
        import yaml

        path = SPECS_DIR / f"{spec_key}.yaml"
        _spec_cache[spec_key] = (
            yaml.safe_load(path.read_text(encoding="utf-8")) or {} if path.exists() else {}
        )
    return _spec_cache[spec_key]


def _resolve(node: object, spec: dict) -> dict | None:
    """Follow local ``#/components/...`` $refs, guarding against cycles."""
    seen: set[str] = set()
    while isinstance(node, dict) and "$ref" in node:
        ref = node["$ref"]
        if not isinstance(ref, str) or not ref.startswith("#/") or ref in seen:
            return None
        seen.add(ref)
        cur: object = spec
        for part in ref[2:].split("/"):
            cur = cur.get(part) if isinstance(cur, dict) else None
            if cur is None:
                return None
        node = cur
    return node if isinstance(node, dict) else None


def _prop_type(prop: dict) -> str | None:
    """Normalize ``type`` (OpenAPI 3.1 allows ``["string", "null"]``)."""
    t = prop.get("type")
    if isinstance(t, list):
        non_null = [x for x in t if x != "null"]
        return non_null[0] if len(non_null) == 1 and isinstance(non_null[0], str) else None
    return t if isinstance(t, str) else None


def _cli_name(prop_name: str) -> str:
    return prop_name.replace("_", "-").lower()


def _example(prop: dict) -> str | None:
    """Scalar ``example`` (OpenAPI) or first ``examples`` entry (2020-12)."""
    examples = prop.get("examples")
    candidates = [prop.get("example")] + (examples if isinstance(examples, list) else [])
    for value in candidates:
        if isinstance(value, (str, int, float, bool)) and str(value).strip():
            return str(value)
    return None


def _hint(prop: dict, cli_name: str) -> str:
    desc = prop.get("description")
    if isinstance(desc, str) and desc.strip():
        return re.sub(r"\s+", " ", desc).strip()
    example = _example(prop)
    if example is not None:
        return f"e.g. {example}"
    return f"Enter {cli_name}"


def _enum_choices(prop: dict) -> list[str]:
    return [c for c in prop.get("enum") or [] if isinstance(c, str)]


def _value_hint(prop: dict, prop_type: str, choices: list[str]) -> str:
    if choices:
        if len(choices) <= 6:
            return "One of: " + ", ".join(choices)
        return "One of: " + ", ".join(choices[:6]) + f", … ({len(choices)} choices)"
    if prop_type == "boolean":
        return "true or false"
    if prop_type in {"integer", "number"}:
        return "A number"
    if prop_type == "array":
        return "One or more values"
    example = _example(prop)
    if example is not None:
        return f"e.g. {example}"
    return "Text value"


class _Unsupported(Exception):
    """Raised while building an entry to skip the resource with a reason."""

    def __init__(self, reason: str):
        super().__init__(reason)
        self.reason = reason


def _flatten_schema(schema: dict, spec: dict) -> tuple[dict, set[str], list[tuple[str | None, list]]]:
    """Merge allOf branches; collect properties, required names, and
    top-level anyOf/oneOf groups as ``(title, [variant, ...])`` tuples."""
    props: dict[str, object] = {}
    required: set[str] = set()
    groups: list[tuple[str | None, list]] = []
    stack: list[object] = [schema]
    while stack:
        node = _resolve(stack.pop(0), spec)
        if node is None:
            continue
        stack.extend(node.get("allOf") or [])
        for key, value in (node.get("properties") or {}).items():
            props.setdefault(key, value)
        required.update(x for x in node.get("required") or [] if isinstance(x, str))
        for key in ("anyOf", "oneOf"):
            direct: list = []
            for entry in node.get(key) or []:
                resolved = _resolve(entry, spec)
                nested = (resolved or {}).get("oneOf") or (resolved or {}).get("anyOf")
                if nested:
                    # Titled wrapper group, e.g. address_type / container_type.
                    groups.append(((resolved or {}).get("title"), list(nested)))
                else:
                    direct.append(entry)
            if direct:
                # Bare list of variants (e.g. the folder/snippet/device oneOf).
                groups.append((node.get("title"), direct))
    return props, required, groups


def _variant_prop(variant: object, spec: dict) -> tuple[str, dict] | None:
    """Return (prop_name, prop_schema) when the variant is a single-scalar-
    property object, else None."""
    node = _resolve(variant, spec)
    if node is None:
        return None
    props = node.get("properties")
    if not isinstance(props, dict) or len(props) != 1:
        return None
    name = next(iter(props))
    prop = _resolve(props[name], spec)
    if prop is None or _prop_type(prop) not in _SCALAR_TYPES:
        return None
    return str(name), prop


# ---------------------------------------------------------------------------
# Entry builder
# ---------------------------------------------------------------------------

def _classify_property(prop: dict, spec: dict) -> str | None:
    """Return "scalar" | "list" | None (unsupported).  readOnly is handled
    by the caller."""
    prop_type = _prop_type(prop)
    if prop_type in _SCALAR_TYPES:
        return "scalar"
    if prop_type == "array":
        items = _resolve(prop.get("items"), spec)
        if items is not None and _prop_type(items) == "string" and "properties" not in items:
            return "list"
    return None


def _variant_group(groups: list[tuple[str | None, list]], spec: dict) -> tuple[str | None, list[tuple[str, dict]]] | None:
    """Reduce the collected anyOf/oneOf groups to at most one variant group.

    Raises _Unsupported for non-conforming groups or a second variant group.
    """
    variant_groups: list[tuple[str | None, list[tuple[str, dict]]]] = []
    for title, variants in groups:
        parsed = [_variant_prop(v, spec) for v in variants]
        if any(p is None for p in parsed):
            raise _Unsupported("non-conforming anyOf/oneOf variant group")
        names = {p[0] for p in parsed}  # type: ignore[index]
        if names <= _CONTAINER_PROPS:
            continue  # container group — folder comes from context
        variant_groups.append((title, parsed))  # type: ignore[arg-type]
    if len(variant_groups) > 1:
        raise _Unsupported("multiple anyOf/oneOf variant groups")
    return variant_groups[0] if variant_groups else None


def _variant_hint(title: str | None) -> str:
    base = (title or "value").strip()
    for suffix in ("_type", "-type"):
        if base.lower().endswith(suffix) and len(base) > len(suffix):
            base = base[: -len(suffix)]
    base = base.replace("_", " ").replace("-", " ").strip() or "value"
    return f"Choose the {base} type"


def _build_entry(entry: dict) -> dict:
    """Build one FIELD_CATALOG value; raises _Unsupported to skip."""
    spec = _load_spec(entry["spec"])
    operation = ((spec.get("paths") or {}).get(entry["path"]) or {}).get("post") or {}
    body = operation.get("requestBody")
    if not isinstance(body, dict):
        raise _Unsupported("no request body")
    schema = ((body.get("content") or {}).get("application/json") or {}).get("schema")
    if not schema:
        raise _Unsupported("no application/json request body")
    schema = _resolve(schema, spec)
    if schema is None:
        raise _Unsupported("unresolvable schema")

    props, required, groups = _flatten_schema(schema, spec)
    if not props and not groups:
        raise _Unsupported("request schema is not an object")
    variant = _variant_group(groups, spec)
    variant_prop_names = {name for name, _ in variant[1]} if variant else set()

    # Classify top-level properties.
    fields: dict[str, dict] = {}  # api property -> {"cli", "kind", "prop"}
    reserved = {"type", "value"} if variant else set()
    for prop_name, raw in props.items():
        if prop_name in variant_prop_names:
            continue  # handled via the variant type/value pair
        prop = _resolve(raw, spec)
        if prop is None:
            prop = {}
        if prop.get("readOnly"):
            continue  # e.g. id — server-assigned
        kind = _classify_property(prop, spec)
        cli = _cli_name(prop_name)
        clash = cli in reserved or any(f["cli"] == cli for f in fields.values())
        if kind is None or clash:
            if prop_name in required:
                reason = ("required field collides with variant type/value slot"
                          if clash else "required field is a nested object/array")
                raise _Unsupported(reason)
            continue  # optional unsupported field — silently dropped
        fields[prop_name] = {"cli": cli, "kind": kind, "prop": prop}

    if not fields and variant is None:
        raise _Unsupported("no usable fields")

    # --- args ------------------------------------------------------------
    def arg_for(prop_name: str, meta: dict, is_required: bool) -> dict:
        prop = meta["prop"]
        choices = _enum_choices(prop) if _prop_type(prop) == "string" else []
        arg = {
            "name": meta["cli"],
            "kind": "value" if is_required else "keyword",
            "required": is_required,
            "hint": _hint(prop, meta["cli"]),
        }
        if not is_required or choices:
            arg["value_hint"] = _value_hint(prop, _prop_type(prop) or "string", choices)
        if choices:
            arg["choices"] = choices
        # Schema-declared value constraints — enforced at the prompt by
        # _payload_from_fields (app/commands/generated.py) before staging.
        pattern = prop.get("pattern")
        if isinstance(pattern, str) and pattern:
            arg["pattern"] = pattern
        max_length = prop.get("maxLength")
        if isinstance(max_length, int) and not isinstance(max_length, bool) and max_length > 0:
            arg["max_length"] = max_length
        return arg

    required_names = [n for n in fields if n in required]
    required_order = ([n for n in required_names if n == "name"]
                      + sorted(n for n in required_names if n != "name"))
    optional_names = sorted(n for n in fields if n not in required)
    optional_order = ([n for n in optional_names if n == "description"]
                      + [n for n in optional_names if n == "tag"]
                      + [n for n in optional_names if n not in ("description", "tag")])

    args = [arg_for(n, fields[n], True) for n in required_order]
    if variant is not None:
        title, variant_props = variant
        choice_names = [_cli_name(name) for name, _ in variant_props]
        args.append({
            "name": "type",
            "kind": "choice",
            "required": True,
            "choices": choice_names,
            "choice_hints": {
                _cli_name(name): _hint(prop, _cli_name(name)) for name, prop in variant_props
            },
            "hint": _variant_hint(title),
        })
        args.append({
            "name": "value",
            "kind": "value",
            "required": True,
            "hint": "Enter the value for the chosen type",
        })
    args.extend(arg_for(n, fields[n], False) for n in optional_order)

    if not args:
        raise _Unsupported("no usable fields")

    # --- payload ----------------------------------------------------------
    ordered = required_order + optional_order
    payload = {
        "fields": {fields[n]["cli"]: n for n in ordered},
        "list_fields": [fields[n]["cli"] for n in ordered if fields[n]["kind"] == "list"],
        "variant": None,
    }
    if variant is not None:
        payload["variant"] = {
            "type_field": "type",
            "value_field": "value",
            "choices": {_cli_name(name): name for name, _ in variant[1]},
            "choice_hints": {
                _cli_name(name): _hint(prop, _cli_name(name)) for name, prop in variant[1]
            },
        }
    return {"args": args, "payload": payload}


def _build_catalog() -> tuple[dict[str, dict], dict[str, list[str]]]:
    """Return (catalog, skipped-reason -> [commands])."""
    from app.commands.resource_catalog import CATALOG

    catalog: dict[str, dict] = {}
    skipped: dict[str, list[str]] = {}
    for entry in CATALOG:
        if entry["method"] != "POST" or not entry["command"].startswith("set ") or entry["path_params"]:
            continue
        try:
            catalog[entry["command"]] = _build_entry(entry)
        except _Unsupported as exc:
            skipped.setdefault(exc.reason, []).append(entry["command"])
    return dict(sorted(catalog.items())), skipped


# ---------------------------------------------------------------------------
# Rendering
# ---------------------------------------------------------------------------

def _render(catalog: dict[str, dict]) -> str:
    lines = [_HEADER.rstrip("\n")]
    for command, entry in catalog.items():
        lines.append(f"    {command!r}: {{")
        lines.append("        'args': [")
        for arg in entry["args"]:
            lines.append(f"            {arg!r},")
        lines.append("        ],")
        lines.append("        'payload': {")
        payload = entry["payload"]
        lines.append(f"            'fields': {payload['fields']!r},")
        lines.append(f"            'list_fields': {payload['list_fields']!r},")
        variant = payload["variant"]
        if variant is None:
            lines.append("            'variant': None,")
        else:
            lines.append("            'variant': {")
            for key in ("type_field", "value_field", "choices", "choice_hints"):
                lines.append(f"                {key!r}: {variant[key]!r},")
            lines.append("            },")
        lines.append("        },")
        lines.append("    },")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    check_only = "--check" in sys.argv[1:]
    try:
        catalog, skipped = _build_catalog()
    except ModuleNotFoundError:
        print("[warn] PyYAML not installed — cannot regenerate field catalog "
              "(run: uv pip install -e '.[dev]')", file=sys.stderr)
        return 0  # don't fail the pull; catalog just stays as-is

    rendered = _render(catalog)
    current = CATALOG_FILE.read_text(encoding="utf-8") if CATALOG_FILE.exists() else ""
    skipped_count = sum(len(cmds) for cmds in skipped.values())

    if check_only:
        if rendered != current:
            diff = list(difflib.unified_diff(
                current.splitlines(), rendered.splitlines(),
                "app/settings/field_catalog.py (current)",
                "app/settings/field_catalog.py (regenerated)", lineterm="", n=0))
            added = sum(1 for l in diff if l.startswith("+") and not l.startswith("+++"))
            removed = sum(1 for l in diff if l.startswith("-") and not l.startswith("---"))
            print("app/settings/field_catalog.py is STALE "
                  f"(+{added}/-{removed} lines). Run: python dev/generate_field_library.py")
            for line in diff[:20]:
                print(line)
            return 1
        print(f"field catalog current — {len(catalog)} set command(s) with field syntax")
        return 0

    CATALOG_FILE.write_text(rendered, encoding="utf-8")
    print(f"Wrote app/settings/field_catalog.py — {len(catalog)} set command(s) "
          f"with field syntax ({skipped_count} skipped: nested/unsupported)")
    if "--verbose" in sys.argv[1:]:
        for reason in sorted(skipped):
            cmds = skipped[reason]
            print(f"  [skip] {reason} ({len(cmds)}): {', '.join(cmds)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
