#!/usr/bin/env python3
"""Generate app/commands/resource_catalog.py from the pulled SCM specs.

ARC aims for **100% coverage** of NGFW config list endpoints: every folder-scoped
``GET`` collection in the pulled OpenAPI specs should be reachable as a
``show <resource>`` command.  Hand-writing a method + handler per resource does
not scale, so instead:

  1. This script reads ``docs/scm-api/specs/ngfw-*.yaml`` and extracts every
     folder-scoped collection ``GET`` endpoint.
  2. It subtracts the resources already covered by an explicit ``show`` command
     (matched via each command doc's front-matter ``api:`` path).
  3. The remainder is written to ``app/commands/resource_catalog.py`` — and the
     generic factory in ``app/commands/generated.py`` turns each into a real
     (ungated, always-on) ``show <resource>`` command.

Run on every ``docsupdate`` so new pan.dev endpoints become commands
automatically.  ``--check`` reports drift (new uncovered endpoints) without
writing, and is used by the smoke test.
"""

from __future__ import annotations

import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

SPECS_DIR = REPO_ROOT / "docs" / "scm-api" / "specs"
COMMAND_DOCS_DIR = REPO_ROOT / "docs" / "commands"
CATALOG_FILE = REPO_ROOT / "app" / "commands" / "resource_catalog.py"

# Folder-scoped NGFW config domains we auto-expose (spec file → domain key used
# by SCMClient.get_config).  Device-settings and live-ops are intentionally not
# folder-scoped collections and are handled by explicit commands.
_DOMAIN_SPECS = {
    "objects": "ngfw-objects.yaml",
    "security": "ngfw-security.yaml",
    "network": "ngfw-network.yaml",
    "identity": "ngfw-identity.yaml",
}

_DOMAIN_BASE_PATH = {
    "objects": "/config/objects/v1",
    "security": "/config/security/v1",
    "network": "/config/network/v1",
    "identity": "/config/identity/v1",
}


def _collection_paths(spec: dict) -> list[str]:
    """Return folder-scoped collection GET paths (no path parameters)."""
    out = []
    for path, ops in (spec.get("paths") or {}).items():
        if "get" not in {k.lower() for k in ops} or "{" in path:
            continue
        out.append(path)
    return sorted(out)


def _covered_collection_paths() -> set[str]:
    """Full paths already listed by an explicit ``show`` command (front-matter)."""
    from app.settings.command_help import parse_front_matter

    covered: set[str] = set()
    for doc in COMMAND_DOCS_DIR.glob("*.md"):
        text = doc.read_text(encoding="utf-8")
        if not text.startswith("---"):
            continue
        meta, _ = parse_front_matter(text)
        command = str(meta.get("command", ""))
        api = str(meta.get("api", ""))
        if not command.startswith("show ") or "/config/" not in api:
            continue
        # api looks like "GET /config/objects/v1/addresses" — keep the path,
        # drop the method and any trailing /{id}.
        path = api.split()[-1]
        path = path.split("/{")[0].rstrip("/")
        covered.add(path)
    return covered


def _build_catalog() -> list[dict]:
    """Return uncovered {command, domain, path, category} entries from the specs."""
    import yaml

    covered = _covered_collection_paths()
    entries: list[dict] = []
    seen_commands: set[str] = set()
    for domain, spec_name in _DOMAIN_SPECS.items():
        spec_path = SPECS_DIR / spec_name
        if not spec_path.exists():
            continue
        spec = yaml.safe_load(spec_path.read_text(encoding="utf-8")) or {}
        base = _DOMAIN_BASE_PATH[domain]
        for resource_path in _collection_paths(spec):
            full_path = base + resource_path
            if full_path in covered:
                continue
            command = "show " + resource_path.strip("/").replace("/", " ")
            if command in seen_commands:
                continue
            seen_commands.add(command)
            entries.append({
                "command": command,
                "domain": domain,
                "path": resource_path,
                "category": domain,
            })
    return sorted(entries, key=lambda e: e["command"])


def _render(entries: list[dict]) -> str:
    lines = [
        '"""Auto-generated NGFW resource catalog — DO NOT EDIT BY HAND.',
        "",
        "Generated by ``dev/generate_resource_catalog.py`` from the pulled SCM specs.",
        "Each entry becomes a generic, always-on ``show <resource>`` command via",
        "``app/commands/generated.py``.  Regenerate with:",
        "    python dev/generate_resource_catalog.py   (runs automatically on docsupdate)",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "CATALOG: list[dict] = [",
    ]
    for e in entries:
        lines.append(
            f'    {{"command": {e["command"]!r}, "domain": {e["domain"]!r}, '
            f'"path": {e["path"]!r}, "category": {e["category"]!r}}},'
        )
    lines.append("]")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    check_only = "--check" in sys.argv[1:]
    try:
        entries = _build_catalog()
    except ModuleNotFoundError:
        print("[warn] PyYAML not installed — cannot regenerate resource catalog "
              "(run: uv pip install -e '.[dev]')", file=sys.stderr)
        return 0  # don't fail the pull; catalog just stays as-is

    rendered = _render(entries)
    current = CATALOG_FILE.read_text(encoding="utf-8") if CATALOG_FILE.exists() else ""

    if check_only:
        if rendered != current:
            print("app/commands/resource_catalog.py is STALE — new uncovered SCM "
                  "endpoints found. Run: python dev/generate_resource_catalog.py")
            return 1
        print(f"resource catalog current — {len(entries)} auto-generated show command(s)")
        return 0

    CATALOG_FILE.write_text(rendered, encoding="utf-8")
    print(f"Wrote app/commands/resource_catalog.py — {len(entries)} auto-generated "
          "show command(s) for uncovered NGFW config endpoints")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

