"""Auto-generated `show <resource>` commands for 100% NGFW config coverage.

Every folder-scoped list endpoint in the pulled SCM specs that does **not**
already have an explicit command is exposed here as a generic, always-on
``show <resource>`` command.  The resource list lives in
``app/commands/resource_catalog.py`` (generated by
``dev/generate_resource_catalog.py`` from the specs, refreshed on every
``docsupdate``).

These commands are intentionally **ungated** (``feature_flag=""``) so the full
API surface is always available — that is the project policy: 100% coverage,
always.  Each handler calls the generic ``SCMClient.get_config(domain, path,
folder)`` and the result is rendered by the generic list-table fallback in
``ArcShell._render()``.

To add coverage for a brand-new endpoint you do **nothing** by hand: pull specs
with ``docsupdate`` and the catalog + these commands regenerate.
"""

from __future__ import annotations

from typing import Any, Callable

from app.commands.base import CommandDef, ExecutionContext, require_scm

try:
    from app.commands.resource_catalog import CATALOG
except Exception:  # noqa: BLE001 — missing/older catalog must never break startup
    CATALOG = []


def _make_show_handler(domain: str, path: str) -> Callable[[ExecutionContext, dict], Any]:
    """Return a folder-scoped list handler for one resource (closure, not a lambda)."""

    def _show(ctx: ExecutionContext, args: dict) -> Any:
        scm = require_scm(ctx)
        return scm.get_config(domain, path, folder=ctx.folder)

    _show.__name__ = "_auto_" + path.strip("/").replace("/", "_").replace("-", "_")
    return _show


def _humanize(command: str) -> str:
    """'show syslog-server-profiles' -> 'Show syslog server profiles ...'."""
    resource = command[len("show "):].replace("-", " ")
    return f"Show {resource} in the active folder"


def _build() -> dict[str, CommandDef]:
    commands: dict[str, CommandDef] = {}
    for entry in CATALOG:
        command = entry["command"]
        commands[command] = CommandDef(
            description=_humanize(command),
            category=entry["category"],
            scope="folder",
            api_handler=_make_show_handler(entry["domain"], entry["path"]),
            ssh_command=None,
            render="",          # generic list-table fallback in _render()
            feature_flag="",    # ungated — 100% coverage is always on
        )
    return commands


COMMANDS: dict[str, CommandDef] = _build()

