"""ARC feature flags — JSON-driven command switches with a development tier.

The source of truth is the ``settings/features/`` directory — one small JSON
file per domain (``scm-<spec>.json``, ``panos-ops.json``, ``panos-config.json``),
regenerated by ``dev/generate_feature_flags.py``. A legacy
single ``settings/features.json`` is still read if present. Each key is a flag
name, each value is one of three states:

    true   → ON   — command is visible and runnable for everyone
    "dev"  → DEV  — command is under development: hidden for normal users,
                    revealed only when development mode is active
    false  → OFF  — command is hidden and blocked for everyone

Keys starting with ``_`` are comments and ignored.

Development mode lets a team ship work-in-progress commands behind the hidden
``dev`` shell command (or the ``ARC_DEV_MODE`` env var for CI/CD) without
confusing normal users — a ``"dev"`` command only appears once development mode
is switched on.

Precedence (last wins):
  1. settings/features/*.json (per-domain glossary; legacy single-file
     settings/features.json still read first if present)
  2. ARC_FEATURE_<NAME>=on|off|dev  environment variable (CI / one-shot)

When a flag is hidden (OFF, or DEV outside development mode):
  - The command is hidden from ? help output
  - Running it prints how to enable it (and mentions ``dev`` for DEV flags)
  - The CommandDef still exists in the registry (so smoke tests can see it)

Adding a new feature:
  1. Set ``feature_flag='your_flag'`` on the CommandDef (app/commands/*.py)
  2. Run ``python dev/generate_feature_flags.py`` — the flag lands in its
     domain file under settings/features/ (default false); set it to "dev"
     there while building
  3. Flip to ``true`` in that file when ready to ship

Inside ARC:
  feature show              list every flag and its on/dev/off state
  feature enable <flag>     turn one ON for this session
  feature disable <flag>    turn one OFF for this session
  feature dev <flag>        mark one as DEV for this session
  dev                       toggle development mode (reveals DEV commands)
"""

from __future__ import annotations

import json
import logging
import os

from pathlib import Path

from app.paths import FEATURES_DIR, FEATURES_FILE

logger = logging.getLogger(__name__)

# The four states a flag can hold.  These strings are used everywhere a flag's
# state is compared or displayed, so keep them stable.
STATE_ON     = "on"
STATE_DEV    = "dev"
STATE_HIDDEN = "hidden"
STATE_OFF    = "off"

# A loaded feature set maps flag-name → state ("on" | "dev" | "hidden" | "off").
FeatureMap = dict[str, str]

_ENV_PREFIX = "ARC_FEATURE_"

# Synonyms accepted in features.json values and ARC_FEATURE_* env vars.
_ON_WORDS     = {"on", "true", "1", "yes", "enabled"}
_DEV_WORDS    = {"dev", "development", "beta", "wip"}
_HIDDEN_WORDS = {"hidden", "invisible", "stealth"}


def _coerce_state(value: object) -> str:
    """Normalize a raw features.json value into "on" | "dev" | "hidden" | "off".

    Accepts booleans (``true``/``false``) and strings (``"dev"``, ``"hidden"`` …).
    Anything unrecognized is treated as OFF — the safe default.
    """
    if isinstance(value, bool):
        return STATE_ON if value else STATE_OFF
    token = str(value).strip().lower()
    if token in _HIDDEN_WORDS:
        return STATE_HIDDEN
    if token in _DEV_WORDS:
        return STATE_DEV
    if token in _ON_WORDS:
        return STATE_ON
    return STATE_OFF


def _feature_files() -> list[Path]:
    """All flag files, in load order: legacy single file first, then the
    per-domain glossary directory (settings/features/*.json, sorted) — so the
    directory always wins if a flag somehow appears in both."""
    files: list[Path] = []
    if FEATURES_FILE.exists():
        files.append(FEATURES_FILE)
    if FEATURES_DIR.is_dir():
        files.extend(sorted(FEATURES_DIR.glob("*.json")))
    return files


def load_features_with_sources() -> tuple[FeatureMap, dict[str, Path]]:
    """Read every feature file; return (flag→state, flag→owning file).

    Supports a ``_default`` key per file — the state assigned to any flag that
    is absent from the map.  ``_default: false`` (the generated default) is
    already handled by the STATE_OFF fallback in ``feature_state()``, but
    ``_default: "dev"`` requires this loader to store the domain default so
    flags inherit it when absent.
    """
    flags: FeatureMap = {}
    sources: dict[str, Path] = {}

    for path in _feature_files():
        try:
            raw = json.loads(path.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError) as exc:
            logger.warning("Could not read %s: %s", path, exc)
            continue
        if not isinstance(raw, dict):
            continue

        # Read the file-level default (for domains where _default != false).
        file_default = _coerce_state(raw["_default"]) if "_default" in raw else STATE_OFF

        for key, val in raw.items():
            if key.startswith("_"):  # _README / _default / _section_* comments
                continue
            state = _coerce_state(val)
            flags[key] = state
            sources[key] = path

        # Store the file default under a well-known sentinel so feature_state()
        # can use it for flags that are absent (not written because they equal
        # the default).  Only store when the default is non-off so we don't
        # pollute the map with useless entries.
        if file_default != STATE_OFF:
            stem = path.stem  # e.g. "scm-adnsr"
            flags[f"_domain_default_{stem}"] = file_default

    # Environment overrides: ARC_FEATURE_SHOW_ADDRESS=on|dev|off.
    for env_key, env_val in os.environ.items():
        if env_key.startswith(_ENV_PREFIX):
            name = env_key[len(_ENV_PREFIX):].lower()
            flags[name] = _coerce_state(env_val)

    return flags, sources


def load_features() -> FeatureMap:
    """Read all feature files + ARC_FEATURE_<NAME> env overrides.

    Returns a plain dict of flag_name → state string.  Flags live in the
    ``settings/features/`` glossary directory (one small file per domain);
    a legacy ``settings/features.json`` is still honored if present.
    """
    return load_features_with_sources()[0]


def feature_file_for(flag_name: str) -> Path:
    """The file a flag change should persist to.

    Known flags go back to their owning glossary file; brand-new flags (not
    yet emitted by any generator) land in ``settings/features/local.json``.
    """
    _flags, sources = load_features_with_sources()
    return sources.get(flag_name, FEATURES_DIR / "local.json")


def feature_state(flags: FeatureMap, flag_name: str) -> str:
    """Return the raw state of *flag_name* — "on", "dev", or "off".

    An empty *flag_name* (the default on a CommandDef) is always "on" — commands
    without a flag are never gated.  A flag absent from the map is "off".
    """
    if not flag_name:
        return STATE_ON
    return flags.get(flag_name, STATE_OFF)


def is_enabled(flags: FeatureMap, flag_name: str, dev_mode: bool = False) -> bool:
    """Return True when *flag_name* is executable in the current mode.

    * ON     — always executable.
    * HIDDEN — always executable (works but not shown in ``?``).
    * DEV    — executable only when *dev_mode* is True.
    * OFF    — never executable.

    An empty *flag_name* always returns True (ungated command).
    """
    state = feature_state(flags, flag_name)
    if state in (STATE_ON, STATE_HIDDEN):
        return True
    if state == STATE_DEV:
        return dev_mode
    return False


def is_feature_visible(flags: FeatureMap, flag_name: str, dev_mode: bool = False) -> bool:
    """Return True when a command should appear in ``?`` / tab completion.

    * ON     → always visible.
    * HIDDEN → visible only in dev mode (hidden from normal users).
    * DEV    → visible only in dev mode.
    * OFF    → never visible.
    """
    state = feature_state(flags, flag_name)
    if state == STATE_ON:
        return True
    if state in (STATE_DEV, STATE_HIDDEN):
        return dev_mode
    return False


def dev_mode_from_env() -> bool:
    """Return True when ARC_DEV_MODE is set to a truthy value (CI/CD hook)."""
    return os.environ.get("ARC_DEV_MODE", "").strip().lower() in _ON_WORDS

