"""ARC feature flags — JSON-driven command switches with a development tier.

The source of truth is the ``settings/features/`` directory — one small JSON
file per domain (``scm-<spec>.json``, ``panos-ops.json``, ``panos-config.json``),
regenerated by ``app/scripts/generate_feature_flags.py``. A legacy
single ``settings/features.json`` is still read if present. Each key is a flag
name, each value is one of three states:

    true   → ON   — command is visible and runnable for everyone
    "dev"  → DEV  — command is under development: hidden for normal users,
                    revealed only when development mode is active
    false  → OFF  — command is hidden and blocked for everyone

Keys starting with ``_`` are comments and ignored.

Development mode lets a team ship work-in-progress commands behind the hidden
``dev`` shell command (or the ``ARC_DEV_MODE`` env var for CI/CD) without
confusing normal users — a ``"dev"`` command only appears once development mode
is switched on.

Precedence (last wins):
  1. settings/features/*.json (per-domain glossary; legacy single-file
     settings/features.json still read first if present)
  2. ARC_FEATURE_<NAME>=on|off|dev  environment variable (CI / one-shot)

When a flag is hidden (OFF, or DEV outside development mode):
  - The command is hidden from ? help output
  - Running it prints how to enable it (and mentions ``dev`` for DEV flags)
  - The CommandDef still exists in the registry (so smoke tests can see it)

Adding a new feature:
  1. Set ``feature_flag='your_flag'`` on the CommandDef (app/commands/*.py)
  2. Run ``python app/scripts/generate_feature_flags.py`` — the flag lands in its
     domain file under settings/features/ (default false); set it to "dev"
     there while building
  3. Flip to ``true`` in that file when ready to ship

Inside ARC:
  feature show              list every flag and its on/dev/off state
  feature enable <flag>     turn one ON for this session
  feature disable <flag>    turn one OFF for this session
  feature dev <flag>        mark one as DEV for this session
  dev                       toggle development mode (reveals DEV commands)
"""

from __future__ import annotations

import json
import logging
import os

from pathlib import Path

from app.paths import FEATURES_DIR, FEATURES_FILE

logger = logging.getLogger(__name__)

# The four states a flag can hold.  These strings are used everywhere a flag's
# state is compared or displayed, so keep them stable.
STATE_ON     = "on"
STATE_DEV    = "dev"
STATE_HIDDEN = "hidden"
STATE_OFF    = "off"

# A loaded feature set maps flag-name → state ("on" | "dev" | "hidden" | "off").
FeatureMap = dict[str, str]

_ENV_PREFIX = "ARC_FEATURE_"

# Synonyms accepted in features.json values and ARC_FEATURE_* env vars.
_ON_WORDS     = {"on", "true", "1", "yes", "enabled"}
_DEV_WORDS    = {"dev", "development", "beta", "wip"}
_HIDDEN_WORDS = {"hidden", "invisible", "stealth"}

# Command run-scope values (mirror app.commands.base.CommandScope).  Scope is a
# per-command property sourced from code; the feature files may carry optional
# per-command *overrides* (see load_scope_overrides / set_scope_override).
SCOPE_GLOBAL = "global"
SCOPE_FOLDER = "folder"
SCOPE_DEVICE = "device"
SCOPE_REMOTE = "remote"
VALID_SCOPES = (SCOPE_GLOBAL, SCOPE_FOLDER, SCOPE_DEVICE, SCOPE_REMOTE)

# Scopes that require an active device context (`cd <device>`).
DEVICE_SCOPES = (SCOPE_DEVICE, SCOPE_REMOTE)

# Key under which per-command scope overrides live inside a feature file.
_SCOPE_OVERRIDES_KEY = "_scope_overrides"

# Key under which disabled areas (categories) live in local.json.  A disabled
# area is a real OFF gate — its commands are hidden and blocked everywhere.
_DISABLED_AREAS_KEY = "_disabled_areas"


def _coerce_state(value: object) -> str:
    """Normalize a raw features.json value into "on" | "dev" | "hidden" | "off".

    Accepts booleans (``true``/``false``), strings (``"dev"``, ``"hidden"`` …),
    and the forward-compatible object form ``{"state": <value>}`` (extra keys
    ignored).  Anything unrecognized is treated as OFF — the safe default.
    """
    if isinstance(value, dict):
        value = value.get("state", False)
    if isinstance(value, bool):
        return STATE_ON if value else STATE_OFF
    token = str(value).strip().lower()
    if token in _HIDDEN_WORDS:
        return STATE_HIDDEN
    if token in _DEV_WORDS:
        return STATE_DEV
    if token in _ON_WORDS:
        return STATE_ON
    return STATE_OFF


def coerce_scope(value: object) -> str | None:
    """Normalize a scope token to one of VALID_SCOPES, or None if unrecognized."""
    token = str(value).strip().lower()
    return token if token in VALID_SCOPES else None



def _feature_files() -> list[Path]:
    """All flag files, in load order: legacy single file first, then the
    per-domain glossary directory (settings/features/*.json, sorted) — so the
    directory always wins if a flag somehow appears in both."""
    files: list[Path] = []
    if FEATURES_FILE.exists():
        files.append(FEATURES_FILE)
    if FEATURES_DIR.is_dir():
        files.extend(sorted(FEATURES_DIR.glob("*.json")))
    return files


def load_features_with_sources() -> tuple[FeatureMap, dict[str, Path]]:
    """Read every feature file; return (flag→state, flag→owning file).

    Supports a ``_default`` key per file — the state assigned to any flag that
    is absent from the map.  ``_default: false`` (the generated default) is
    already handled by the STATE_OFF fallback in ``feature_state()``, but
    ``_default: "dev"`` requires this loader to store the domain default so
    flags inherit it when absent.
    """
    flags: FeatureMap = {}
    sources: dict[str, Path] = {}

    for path in _feature_files():
        try:
            raw = json.loads(path.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError) as exc:
            logger.warning("Could not read %s: %s", path, exc)
            continue
        if not isinstance(raw, dict):
            continue

        # Read the file-level default (for domains where _default != false).
        file_default = _coerce_state(raw["_default"]) if "_default" in raw else STATE_OFF

        for key, val in raw.items():
            if key.startswith("_"):  # _README / _default / _section_* comments
                continue
            state = _coerce_state(val)
            flags[key] = state
            sources[key] = path

        # Store the file default under a well-known sentinel so feature_state()
        # can use it for flags that are absent (not written because they equal
        # the default).  Only store when the default is non-off so we don't
        # pollute the map with useless entries.
        if file_default != STATE_OFF:
            stem = path.stem  # e.g. "scm-adnsr"
            flags[f"_domain_default_{stem}"] = file_default

    # Environment overrides: ARC_FEATURE_SHOW_ADDRESS=on|dev|off.
    for env_key, env_val in os.environ.items():
        if env_key.startswith(_ENV_PREFIX):
            name = env_key[len(_ENV_PREFIX):].lower()
            flags[name] = _coerce_state(env_val)

    return flags, sources


def load_features() -> FeatureMap:
    """Read all feature files + ARC_FEATURE_<NAME> env overrides.

    Returns a plain dict of flag_name → state string.  Flags live in the
    ``settings/features/`` glossary directory (one small file per domain);
    a legacy ``settings/features.json`` is still honored if present.
    """
    return load_features_with_sources()[0]


def feature_file_for(flag_name: str) -> Path:
    """The file a flag change should persist to.

    Known flags go back to their owning glossary file; brand-new flags (not
    yet emitted by any generator) land in ``settings/features/local.json``.
    """
    _flags, sources = load_features_with_sources()
    return sources.get(flag_name, FEATURES_DIR / "local.json")


def set_feature_state(flag_name: str, state: str) -> Path:
    """Persist one flag *state* ("on" | "dev" | "off") to its owning file.

    Writes the flag into its glossary file under ``settings/features/`` (the
    same file the CLI ``feature enable`` uses), creating ``local.json`` for
    flags with no generated home.  Returns the file that was written.

    This is the single source of truth for persisting a flag change — both the
    ``feature`` shell command and the browser GUI server call it, so the two
    can never diverge on how/where a flag is stored.  Callers that hold live
    shell state (``self._features`` + the visible-keys cache) are responsible
    for updating it after this returns.

    Raises ``RuntimeError`` if the owning file cannot be read or written.
    """
    target = feature_file_for(flag_name)
    try:
        raw = json.loads(target.read_text(encoding="utf-8")) if target.exists() else {}
    except (json.JSONDecodeError, OSError) as exc:
        raise RuntimeError(f"Could not read {target.name}: {exc}") from exc
    if not isinstance(raw, dict):
        raise RuntimeError(f"{target.name} must contain a JSON object")

    normalized = _coerce_state(state)
    raw_value: bool | str
    if normalized == STATE_ON:
        raw_value = True
    elif normalized == STATE_DEV:
        raw_value = "dev"
    elif normalized == STATE_HIDDEN:
        raw_value = "hidden"
    else:
        raw_value = False

    raw[flag_name] = raw_value
    try:
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(json.dumps(raw, indent=2) + "\n", encoding="utf-8")
    except OSError as exc:
        raise RuntimeError(f"Could not write {target.name}: {exc}") from exc
    return target


# ---------------------------------------------------------------------------
# Per-command scope overrides — optional corrections to the code-default scope.
#
# Scope (global/folder/device) is a per-command property defined in code
# (CommandDef.scope).  Operators may override it per command; overrides live in
# settings/features/local.json under ``_scope_overrides`` so they survive
# regeneration, but the loader honors ``_scope_overrides`` found in ANY file.
# ---------------------------------------------------------------------------

def load_scope_overrides() -> dict[str, str]:
    """Return {command_key -> scope} merged from every feature file.

    Only well-formed entries (scope in VALID_SCOPES) are kept.  Later files win
    on collision, matching the load order in ``_feature_files()``.
    """
    overrides: dict[str, str] = {}
    for path in _feature_files():
        try:
            raw = json.loads(path.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError):
            continue
        if not isinstance(raw, dict):
            continue
        block = raw.get(_SCOPE_OVERRIDES_KEY)
        if not isinstance(block, dict):
            continue
        for cmd_key, scope in block.items():
            norm = coerce_scope(scope)
            if norm is not None:
                overrides[str(cmd_key)] = norm
    return overrides


def set_scope_override(command_key: str, scope: str | None) -> Path:
    """Set or clear a per-command scope override in ``local.json``.

    *scope* of None (or an unrecognized value) removes the override.  Returns
    the file written (always ``local.json`` — the regeneration-proof home).

    Raises ``RuntimeError`` if the file cannot be read or written.
    """
    target = FEATURES_DIR / "local.json"
    try:
        raw = json.loads(target.read_text(encoding="utf-8")) if target.exists() else {}
    except (json.JSONDecodeError, OSError) as exc:
        raise RuntimeError(f"Could not read {target.name}: {exc}") from exc
    if not isinstance(raw, dict):
        raise RuntimeError(f"{target.name} must contain a JSON object")

    block = raw.get(_SCOPE_OVERRIDES_KEY)
    if not isinstance(block, dict):
        block = {}

    norm = coerce_scope(scope) if scope is not None else None
    if norm is None:
        block.pop(command_key, None)
    else:
        block[command_key] = norm

    if block:
        raw[_SCOPE_OVERRIDES_KEY] = block
    else:
        raw.pop(_SCOPE_OVERRIDES_KEY, None)

    try:
        target.parent.mkdir(parents=True, exist_ok=True)
        if raw:
            target.write_text(json.dumps(raw, indent=2) + "\n", encoding="utf-8")
        elif target.exists():
            # Nothing left to store — remove the empty file to avoid clutter.
            target.unlink()
    except OSError as exc:
        raise RuntimeError(f"Could not write {target.name}: {exc}") from exc
    return target


def effective_scope(overrides: dict[str, str], command_key: str, code_scope: str) -> str:
    """Return the run scope for *command_key* — override if set, else code scope."""
    return overrides.get(command_key, code_scope)


# ---------------------------------------------------------------------------
# Area (category) enablement — a real master switch for a whole area.
#
# A DISABLED area is turned OFF everywhere: its commands are hidden from ?,
# tab-completion and help, blocked at execution, and removed from every feature
# editor section.  It is a master gate ABOVE the per-feature flags — individual
# flag values are preserved and restored when the area is re-enabled.  Stored in
# local.json under ``_disabled_areas`` so it survives regeneration.
# ---------------------------------------------------------------------------

def load_disabled_areas() -> set[str]:
    """Return the set of area/category keys that are fully disabled."""
    disabled: set[str] = set()
    for path in _feature_files():
        try:
            raw = json.loads(path.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError):
            continue
        if not isinstance(raw, dict):
            continue
        block = raw.get(_DISABLED_AREAS_KEY)
        if isinstance(block, list):
            disabled.update(str(x) for x in block)
    return disabled


def set_area_disabled(category: str, disabled: bool) -> Path:
    """Add/remove *category* from local.json ``_disabled_areas``. Returns the file."""
    target = FEATURES_DIR / "local.json"
    try:
        raw = json.loads(target.read_text(encoding="utf-8")) if target.exists() else {}
    except (json.JSONDecodeError, OSError) as exc:
        raise RuntimeError(f"Could not read {target.name}: {exc}") from exc
    if not isinstance(raw, dict):
        raise RuntimeError(f"{target.name} must contain a JSON object")

    current = raw.get(_DISABLED_AREAS_KEY)
    areas = set(current) if isinstance(current, list) else set()
    if disabled:
        areas.add(category)
    else:
        areas.discard(category)

    if areas:
        raw[_DISABLED_AREAS_KEY] = sorted(areas)
    else:
        raw.pop(_DISABLED_AREAS_KEY, None)

    try:
        target.parent.mkdir(parents=True, exist_ok=True)
        if raw:
            target.write_text(json.dumps(raw, indent=2) + "\n", encoding="utf-8")
        elif target.exists():
            target.unlink()
    except OSError as exc:
        raise RuntimeError(f"Could not write {target.name}: {exc}") from exc
    return target


def is_area_enabled(disabled_areas: set[str], category: str) -> bool:
    """Return True unless *category* is in the disabled set."""
    return category not in disabled_areas


# ---------------------------------------------------------------------------
# File-level meta editing — _default and _carry, surfaced with friendly names.
# ---------------------------------------------------------------------------

def set_file_meta(
    domain_stem: str,
    *,
    default: str | None = None,
    carry: bool | None = None,
) -> Path:
    """Set ``_default`` and/or ``_carry`` on a specific domain feature file.

    *domain_stem* is the file stem (e.g. ``"scm-ngfw-objects"``).  Only the
    provided fields are changed.  Returns the file written.

    Raises ``RuntimeError`` if the file cannot be read or written.
    """
    target = FEATURES_DIR / f"{domain_stem}.json"
    try:
        raw = json.loads(target.read_text(encoding="utf-8")) if target.exists() else {}
    except (json.JSONDecodeError, OSError) as exc:
        raise RuntimeError(f"Could not read {target.name}: {exc}") from exc
    if not isinstance(raw, dict):
        raise RuntimeError(f"{target.name} must contain a JSON object")

    if default is not None:
        state = _coerce_state(default)
        raw["_default"] = {STATE_ON: True, STATE_DEV: "dev", STATE_HIDDEN: "hidden"}.get(state, False)
    if carry is not None:
        raw["_carry"] = bool(carry)

    try:
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(json.dumps(raw, indent=2) + "\n", encoding="utf-8")
    except OSError as exc:
        raise RuntimeError(f"Could not write {target.name}: {exc}") from exc
    return target


def load_file_meta() -> dict[str, dict]:
    """Return {domain_stem -> {default, carry, readme}} for every feature file."""
    meta: dict[str, dict] = {}
    if not FEATURES_DIR.is_dir():
        return meta
    for path in sorted(FEATURES_DIR.glob("*.json")):
        try:
            raw = json.loads(path.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError):
            continue
        if not isinstance(raw, dict):
            continue
        readme = raw.get("_README", "")
        if isinstance(readme, list):
            readme = " ".join(str(x) for x in readme)
        meta[path.stem] = {
            "default": _coerce_state(raw["_default"]) if "_default" in raw else STATE_OFF,
            "carry": bool(raw.get("_carry", False)),
            "readme": readme,
        }
    return meta


def feature_state(flags: FeatureMap, flag_name: str) -> str:
    """Return the raw state of *flag_name* — "on", "dev", or "off".

    An empty *flag_name* (the default on a CommandDef) is always "on" — commands
    without a flag are never gated.  A flag absent from the map is "off".
    """
    if not flag_name:
        return STATE_ON
    return flags.get(flag_name, STATE_OFF)


def is_enabled(flags: FeatureMap, flag_name: str, dev_mode: bool = False) -> bool:
    """Return True when *flag_name* is executable in the current mode.

    * ON     — always executable.
    * HIDDEN — always executable (works but not shown in ``?``).
    * DEV    — executable only when *dev_mode* is True.
    * OFF    — never executable.

    An empty *flag_name* always returns True (ungated command).
    """
    state = feature_state(flags, flag_name)
    if state in (STATE_ON, STATE_HIDDEN):
        return True
    if state == STATE_DEV:
        return dev_mode
    return False


def is_feature_visible(flags: FeatureMap, flag_name: str, dev_mode: bool = False) -> bool:
    """Return True when a command should appear in ``?`` / tab completion.

    * ON     → always visible.
    * HIDDEN → visible only in dev mode.
    * DEV    → visible only in dev mode.
    * OFF    → never visible (dev mode does not reveal blocked commands).
    """
    if not flag_name:
        return True
    state = feature_state(flags, flag_name)
    if state == STATE_ON:
        return True
    if state == STATE_OFF:
        return False
    # STATE_DEV and STATE_HIDDEN — visible only in dev mode
    return dev_mode


def dev_mode_from_env() -> bool:
    """Return True when ARC_DEV_MODE is set to a truthy value (CI/CD hook)."""
    return os.environ.get("ARC_DEV_MODE", "").strip().lower() in _ON_WORDS
