#!/usr/bin/env python3
"""Generate app/settings/request_schemas.py from the pulled SCM OpenAPI specs.

A route-keyed request-body schema so ANY staged write can be validated against
the schema of the endpoint it actually hits — covering generated commands,
hand-written commands, and future features uniformly, because it keys off the
API operation (method + gateway base_url + path template), not the CLI command.

For every ``paths → {path} → {POST|PUT|PATCH}`` with an ``application/json``
request body, emit a compact record:

    {"method", "base_url", "path",           # the route key
     "required": [api-field, ...],           # readOnly + "id" excluded
     "props":    {api-field: {constraints}}, # only fields that carry a constraint
     "variants": [[member, ...], ...]}       # oneOf/anyOf groups (≥1 must be present)

Consumed by ``app/commands/request_validate.py`` (used by `set` staging,
`commit check`, and the `commit` pre-flight).  Regenerate:
    python app/scripts/generate_request_schemas.py   (runs on docsupdate / catalog rebuild)

DELETE has no request body in any spec, so it is not emitted.  Non-JSON bodies
(multipart uploads) are skipped.  The ``cdug`` spec has no ``servers:`` block, so
its routes get a blank base_url and simply go unmatched at runtime (graceful).
"""
from __future__ import annotations

import difflib
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(REPO_ROOT))
sys.path.insert(0, str(Path(__file__).resolve().parent))  # sibling generator imports

# Reuse the spec plumbing from the field-library generator (single source).
from generate_field_library import (  # noqa: E402
    SPECS_DIR,
    _enum_choices,
    _flatten_schema,
    _prop_type,
    _resolve,
)

OUT_FILE = REPO_ROOT / "app" / "settings" / "request_schemas.py"

_WRITE_METHODS = ("post", "put", "patch")
#: Never a user-supplied body field — server-assigned on create, path param on update.
_SERVER_FIELDS = {"id"}

_HEADER = '''"""AUTO-GENERATED request-body schemas — DO NOT EDIT BY HAND.

Generated by ``app/scripts/generate_request_schemas.py`` from the pulled SCM
OpenAPI specs.  Route-keyed (method, base_url, path-template) request-body
constraints, consumed by ``app/commands/request_validate.py``.  Regenerate:
    python app/scripts/generate_request_schemas.py   (runs on docsupdate / catalog rebuild)
"""

REQUEST_SCHEMAS = [
'''


def _constraints(prop: dict, spec: dict) -> dict:
    """Collect the validatable constraints from one property schema."""
    p = _resolve(prop, spec)
    if p is None:
        p = prop if isinstance(prop, dict) else {}
    out: dict = {}
    enum = _enum_choices(p)
    if enum:
        out["enum"] = enum
    for key in ("maxLength", "minLength", "pattern", "minimum", "maximum", "maxItems"):
        val = p.get(key)
        if val is not None:
            out[key] = val
    if _prop_type(p) == "array":
        items = _resolve(p.get("items"), spec) or {}
        items_enum = _enum_choices(items)
        if items_enum:
            out["items_enum"] = items_enum
    return out


def _group_member_names(variants: list, spec: dict) -> list[str]:
    """The distinguishing property names across one anyOf/oneOf group."""
    names: set[str] = set()
    for variant in variants:
        node = _resolve(variant, spec) or {}
        for key in (node.get("properties") or {}):
            names.add(str(key))
    return sorted(names)


def _is_readonly(node: object, spec: dict) -> bool:
    resolved = _resolve(node, spec)
    return bool(isinstance(resolved, dict) and resolved.get("readOnly"))


def _build_records() -> list[dict]:
    import yaml  # noqa: F401 — surfaced as ModuleNotFoundError by _load_spec

    records: dict[tuple, dict] = {}
    for spec_path in sorted(SPECS_DIR.glob("*.yaml")):
        spec = yaml.safe_load(spec_path.read_text(encoding="utf-8")) or {}
        if not isinstance(spec, dict):
            continue
        base_url = ((spec.get("servers") or [{}])[0] or {}).get("url", "") or ""
        for path, item in (spec.get("paths") or {}).items():
            if not isinstance(item, dict):
                continue
            for method in _WRITE_METHODS:
                op = item.get(method)
                if not isinstance(op, dict):
                    continue
                body = op.get("requestBody")
                if not isinstance(body, dict):
                    continue
                schema_node = ((body.get("content") or {}).get("application/json") or {}).get("schema")
                if not schema_node:
                    continue  # non-JSON body (multipart upload) → skip
                schema = _resolve(schema_node, spec)
                if schema is None:
                    continue
                props, required, groups = _flatten_schema(schema, spec)

                req_out = sorted(
                    r for r in required
                    if r not in _SERVER_FIELDS and not _is_readonly(props.get(r), spec)
                )
                props_out: dict[str, dict] = {}
                for name, raw in props.items():
                    if _is_readonly(raw, spec):
                        continue
                    cons = _constraints(raw, spec)
                    if cons:
                        props_out[str(name)] = cons
                variants_out = [
                    names for _title, variants in groups
                    if (names := _group_member_names(variants, spec))
                ]

                if not req_out and not props_out and not variants_out:
                    continue  # nothing to validate

                key = (method.upper(), base_url, str(path))
                records.setdefault(key, {
                    "method": method.upper(),
                    "base_url": base_url,
                    "path": str(path),
                    "required": req_out,
                    "props": props_out,
                    "variants": variants_out,
                })
    return [records[k] for k in sorted(records)]


def _render(records: list[dict]) -> str:
    lines = [_HEADER.rstrip("\n")]
    for rec in records:
        # json.dumps yields valid Python literals here (no bool/None values).
        lines.append("    " + json.dumps(rec, sort_keys=True) + ",")
    lines.append("]")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    check_only = "--check" in sys.argv[1:]
    try:
        records = _build_records()
    except ModuleNotFoundError:
        print("[warn] PyYAML not installed — cannot regenerate request schemas "
              "(run: uv pip install -e '.[dev]')", file=sys.stderr)
        return 0
    rendered = _render(records)
    current = OUT_FILE.read_text(encoding="utf-8") if OUT_FILE.exists() else ""

    if check_only:
        if rendered != current:
            diff = list(difflib.unified_diff(
                current.splitlines(), rendered.splitlines(),
                "app/settings/request_schemas.py (current)",
                "app/settings/request_schemas.py (regenerated)", lineterm="", n=0))
            added = sum(1 for l in diff if l.startswith("+") and not l.startswith("+++"))
            removed = sum(1 for l in diff if l.startswith("-") and not l.startswith("---"))
            print("app/settings/request_schemas.py is STALE "
                  f"(+{added}/-{removed} lines). Run: python app/scripts/generate_request_schemas.py")
            for line in diff[:20]:
                print(line)
            return 1
        print(f"request schemas current — {len(records)} write route(s)")
        return 0

    OUT_FILE.write_text(rendered, encoding="utf-8")
    print(f"Wrote app/settings/request_schemas.py — {len(records)} write route(s)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
